FROM nginx:alpine

COPY . /usr/share/nginx/html/

RUN echo 'server { \
    listen 80; \
    client_max_body_size 50M; \
    client_body_buffer_size 50M; \
    location / { \
        root /usr/share/nginx/html; \
        index index.html; \
        try_files $uri $uri/ /index.html; \
    } \
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]