name = "ai-chat-frontend"
compatibility_date = "2024-08-20"

[env.production]
routes = [
  { pattern = "your-domain.com", zone_name = "your-domain.com" }
]

[[env.production.services]]
binding = "API"
service = "your-api-worker"
